# Generated by Django 4.0.3 on 2022-04-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_expense_expense_type_alter_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
