# Generated by Django 4.0.3 on 2022-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_password_profile_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password1',
        ),
    ]
