# Generated by Django 4.0.3 on 2022-04-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userdetails_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
