# Generated by Django 4.0.3 on 2022-04-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_expense_username_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
